### ISSUE TITLE
No module named '_init_paths'

### ISSUE THREAD

**Issue by ys7yoo** [ys7yoo/HRNet#1]
```
  File "tools/test.py", line 24, in <module>
    import _init_paths
ModuleNotFoundError: No module named '_init_paths'
```

**Comment by ys7yoo** [comment]
https://github.com/tiancity-NJU/da-faster-rcnn-PyTorch/issues/1

**Comment by ys7yoo** [comment]
https://stackoverflow.com/questions/2860153/how-do-i-get-the-parent-directory-in-python

**Comment by ys7yoo** [comment]
fixed
Use `init_paths.py` instead

**Comment by airflycode** [comment]
i got the same problum in another code,witch is Posted in CVPR2020. 
how to use init_paths.py instead the "import" , would u please tell me?
thanks for your time
